language: php

php: '8.0'

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/php-cs-fixer fix src/ --verbose --dry-run --stop-on-violation
  - ./vendor/bin/php-cs-fixer fix tests/ --verbose --dry-run --stop-on-violation

notifications:
  email:
    on_success: never
    on_failure: never